/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofarmacia;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel Arriola
 */
public class CompraProductos extends javax.swing.JPanel {

     Conexion conectar=new Conexion();
   Connection ConectarBD=conectar.getConection();
   ResultSet rs;
   PreparedStatement insertar;
   PreparedStatement Actualizar;
   Statement st;
   DefaultTableModel Modelo=new DefaultTableModel();
    public CompraProductos() {
        initComponents();
       
        Modelo.addColumn("CodigoCompra");
        Modelo.addColumn("CodigoProducto");
        Modelo.addColumn("Nombre Proveedor");
        Modelo.addColumn("Nombre Producto");
        Modelo.addColumn("Precio");
        Modelo.addColumn("Cantidad");
        Modelo.addColumn("CostoTotal");
        
        this.ComprasTB.setModel(Modelo);
        txtFecha.setDisabledTextColor(Color.BLUE);
        txtFecha.setText(Fecha());//pasamos la fecha al txtFecha
        txtFecha.setEnabled(false);//para que no se edite la fecha
        Bloquear();
        CargarNumeroCompra();
        ImprimirBT.setVisible(false);
        CompraBT.setEnabled(false);
        AgregarBoton.setEnabled(false);
        EliminarBT.setEnabled(false);
        CancelarBoton.setEnabled(false);
        
    }
public void CargarNumeroCompra(){
    String CodigoFactura=idCompras(); //cargamos el id de venta 
        int factura=Integer.parseInt(CodigoFactura);//comvertimos el id tipo int
        int resul=1+factura;// le sumamos 1
        String mostraCodigoFa=Integer.toString(resul);
        txtNumeroCompra.setDisabledTextColor(Color.BLUE);
        txtNumeroCompra.setText(mostraCodigoFa);// pasamos el id
        txtNumeroCompra.setEnabled(false);// para que no se pueda editar
}
public void Bloquear(){
    CargarPeroducto.setEnabled(false);
    ProveedorCargar.setEnabled(false);
    
}
public void Desbloquear(){
    CargarPeroducto.setEnabled(true);
    ProveedorCargar.setEnabled(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        txtCodigoProveedor = new javax.swing.JTextField();
        ProveedorCargar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtNombreProducto = new javax.swing.JTextField();
        CodigoProductosCon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        CargarPeroducto = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtNumeroCompra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        EliminarBT = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ImprimirBT = new javax.swing.JButton();
        NuevaCompraBoton = new javax.swing.JButton();
        CompraBT = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ComprasTB = new rojerusan.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        txtTotalPagar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(110, 207, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(110, 207, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Proveedor");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo Proveedor");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 108, 30));
        jPanel4.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 30, 210, 30));

        txtCodigoProveedor.setEditable(false);
        txtCodigoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProveedorActionPerformed(evt);
            }
        });
        jPanel4.add(txtCodigoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 110, 30));

        ProveedorCargar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProveedorCargar.setForeground(new java.awt.Color(0, 0, 0));
        ProveedorCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cargar.png"))); // NOI18N
        ProveedorCargar.setText("CARGAR DATOS PROVEEDOR");
        ProveedorCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProveedorCargar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ProveedorCargar.setIconTextGap(15);
        ProveedorCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorCargarActionPerformed(evt);
            }
        });
        jPanel4.add(ProveedorCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 250, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 130));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        jPanel5.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 210, 30));

        CodigoProductosCon.setEditable(false);
        CodigoProductosCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoProductosConKeyTyped(evt);
            }
        });
        jPanel5.add(CodigoProductosCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Producto");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Codigo Producto");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 108, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 30));

        txtPrecioCompra.setEditable(false);
        txtPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCompraActionPerformed(evt);
            }
        });
        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyTyped(evt);
            }
        });
        jPanel5.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Existencia");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 70, 30));

        txtExistencia.setEditable(false);
        jPanel5.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 70, 30));

        CargarPeroducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarPeroducto.setForeground(new java.awt.Color(0, 0, 0));
        CargarPeroducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cargar.png"))); // NOI18N
        CargarPeroducto.setText("CARGAR DATOS PRODUCTO");
        CargarPeroducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargarPeroducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CargarPeroducto.setIconTextGap(15);
        CargarPeroducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarPeroductoActionPerformed(evt);
            }
        });
        jPanel5.add(CargarPeroducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 250, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 530, 180));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Costo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 530, 90));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FECHA COMPRA");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 180, 48));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel7.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 80, 180, 53));

        txtNumeroCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel7.add(txtNumeroCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 53));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NUMERO  COMPRA");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 170, 190, 48));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 300, 330));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarBoton.setForeground(new java.awt.Color(0, 0, 0));
        AgregarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Agregar.png"))); // NOI18N
        AgregarBoton.setText("AGREGAR");
        AgregarBoton.setContentAreaFilled(false);
        AgregarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AgregarBoton.setIconTextGap(15);
        AgregarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Agregar30.png"))); // NOI18N
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });
        jPanel8.add(AgregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 60));

        CancelarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelarBoton.setForeground(new java.awt.Color(0, 0, 0));
        CancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        CancelarBoton.setText("LIMPIAR");
        CancelarBoton.setContentAreaFilled(false);
        CancelarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CancelarBoton.setIconTextGap(15);
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });
        jPanel8.add(CancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 180, 60));

        EliminarBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EliminarBT.setForeground(new java.awt.Color(0, 0, 0));
        EliminarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Elimina48.png"))); // NOI18N
        EliminarBT.setText("ELIMINAR");
        EliminarBT.setContentAreaFilled(false);
        EliminarBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarBT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EliminarBT.setIconTextGap(15);
        EliminarBT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Elimina32.png"))); // NOI18N
        EliminarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBTActionPerformed(evt);
            }
        });
        jPanel8.add(EliminarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 180, 60));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 620, 90));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        ImprimirBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ImprimirBT.setForeground(new java.awt.Color(0, 0, 0));
        ImprimirBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Imprimir (2).png"))); // NOI18N
        ImprimirBT.setText("IMPRIMIR");
        ImprimirBT.setContentAreaFilled(false);
        ImprimirBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImprimirBT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ImprimirBT.setIconTextGap(15);
        ImprimirBT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Imprimir32.png"))); // NOI18N
        ImprimirBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirBTActionPerformed(evt);
            }
        });

        NuevaCompraBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NuevaCompraBoton.setForeground(new java.awt.Color(0, 0, 0));
        NuevaCompraBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/NuevaVC.png"))); // NOI18N
        NuevaCompraBoton.setText("NUEVA COMPRA");
        NuevaCompraBoton.setContentAreaFilled(false);
        NuevaCompraBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevaCompraBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        NuevaCompraBoton.setIconTextGap(15);
        NuevaCompraBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Nueva32.png"))); // NOI18N
        NuevaCompraBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCompraBotonActionPerformed(evt);
            }
        });

        CompraBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CompraBT.setForeground(new java.awt.Color(0, 0, 0));
        CompraBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Guardar48.png"))); // NOI18N
        CompraBT.setText("REALIZAR COMPRA");
        CompraBT.setContentAreaFilled(false);
        CompraBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CompraBT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CompraBT.setIconTextGap(15);
        CompraBT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/guardar32.png"))); // NOI18N
        CompraBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CompraBT, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NuevaCompraBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImprimirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(NuevaCompraBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CompraBT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ImprimirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 280, 330));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(0, 0, 0));

        ComprasTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(ComprasTB);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total a pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        txtTotalPagar.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotalPagar.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProveedorActionPerformed

    private void ProveedorCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorCargarActionPerformed
        RegistroProveedores pro=new RegistroProveedores();
        pro.setVisible(true);
    }//GEN-LAST:event_ProveedorCargarActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void CodigoProductosConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoProductosConKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_CodigoProductosConKeyTyped

    private void txtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCompraActionPerformed

    private void txtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyTyped
        char v=evt.getKeyChar();
        if((v<'0'||v>'9')&&(v<'.'||v>'.'))evt.consume();
    }//GEN-LAST:event_txtPrecioCompraKeyTyped

    private void CargarPeroductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarPeroductoActionPerformed
        //ProductosNew pro=new ProductosNew();
        MostrarProductosCompra pro=new MostrarProductosCompra();
        pro.setVisible(true);
    }//GEN-LAST:event_CargarPeroductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed

        if(txtCantidad.getText().trim().isEmpty()||txtExistencia.getText().trim().isEmpty()||txtPrecioCompra.getText().trim().isEmpty()||CodigoProductosCon.getText().trim().isEmpty()||txtNombreProducto.getText().trim().isEmpty()||txtNombreProveedor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "POR FAVOR LLENE LOS CAMPOS");

        }else {
            int CantidadV=Integer.parseInt(txtCantidad.getText());
            int existenciap=Integer.parseInt(txtExistencia.getText());
            if(CantidadV>0){
                  llamar();
                  CalcularTotal_Ventas();
                  txtCantidad.setText("");
                  txtCostoTotal.setText("");
                   CompraBT.setEnabled(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "La Cantidad No puede ser 0");
            }
        }
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void CompraBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraBTActionPerformed
if(JOptionPane.showConfirmDialog(null,"DESEA REALIZAR LA COMPRA" ,"",JOptionPane.YES_NO_OPTION)==0){
        if(txtNombreProveedor.getText().trim().isEmpty()||txtCodigoProveedor.getText().trim().isEmpty()||txtNombreProducto.getText().trim().isEmpty()||txtPrecioCompra.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "POR FAVOR LLENE LOS CAMPOS");
} else {
    InsertarCompra();
        RealizarCompra();
        ActualizarExistencia();
}
}
    }//GEN-LAST:event_CompraBTActionPerformed

    private void EliminarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBTActionPerformed
     eliminar();
    }//GEN-LAST:event_EliminarBTActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
       EliminarAgregados();
       Limpiar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void NuevaCompraBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCompraBotonActionPerformed
       EliminarAgregados();
       CargarNumeroCompra();
       Desbloquear();
       Limpiar();
       
        AgregarBoton.setEnabled(true);
        EliminarBT.setEnabled(true);
        CancelarBoton.setEnabled(true);
    }//GEN-LAST:event_NuevaCompraBotonActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        if(txtCantidad.getText().trim().isEmpty()||txtPrecioCompra.getText().trim().isEmpty()){
        
    } else{
        CostoTotal();
    }
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void ImprimirBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImprimirBTActionPerformed

    public void llamar(){
    String idVenta=idCompras();
    int codiV=Integer.parseInt(idVenta);
    int resul=1+codiV;
    String idVentaC=Integer.toString(resul);
    String cargar[]= new String[7];
  
    float precio=Float.parseFloat(txtPrecioCompra.getText());
    int Cantidad=Integer.parseInt(txtCantidad.getText());
    float costo=precio*Cantidad;
    String CostoTotal=Float.toString(costo);
    cargar[0]=txtNumeroCompra.getText();
    cargar[1]=CodigoProductosCon.getText();
    cargar[2]=txtNombreProveedor.getText();
    cargar[3]=txtNombreProducto.getText();
    cargar[4]=txtPrecioCompra.getText();
    cargar[5]=txtCantidad.getText();
    cargar[6]=CostoTotal;
    Modelo.addRow(cargar); 
    
}
    
    public String Fecha(){
    Date fecha=new Date();
    SimpleDateFormat fechaActual=new SimpleDateFormat("yyy-MM-dd");
    return fechaActual.format(fecha);
    
}
public String idCompras(){
    String Consulta="select max(idCompras)as CodigoCompras from Compras";
    String id=null;
    try {
         PreparedStatement Mostra=ConectarBD.prepareStatement(Consulta);
         rs=Mostra.executeQuery();
         if(rs.next()){
             String idCompra=rs.getString("CodigoCompras");
             id=(idCompra);
         }
    } catch (Exception e) {
    }
    return id;
    
}
public void RealizarCompra(){
      try {
          for(int i=0;i<ComprasTB.getRowCount();i++){
              insertar=ConectarBD.prepareStatement("insert into CompraDetalle(idCompras,idProductos,precio,cantidad,costoTotal)values(?,?,?,?,?)");
              insertar.setString(1, ComprasTB.getValueAt(i, 0).toString());
              insertar.setString(2, ComprasTB.getValueAt(i, 1).toString());
              insertar.setString(3, ComprasTB.getValueAt(i, 4).toString());
              insertar.setString(4, ComprasTB.getValueAt(i, 5).toString());
              insertar.setString(5, ComprasTB.getValueAt(i, 6).toString());
              insertar.executeUpdate();
              
          }
          JOptionPane.showMessageDialog(null, "COMPRA REALIZADA CON EXITO");
      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Error"+e.toString());
      }
  }
  public void ActualizarExistencia(){
 
    try {
         for(int i=0;i<ComprasTB.getRowCount();i++){
              Actualizar=ConectarBD.prepareStatement("update Productos set Existencia=Existencia+'"+ComprasTB.getValueAt(i, 5)+"' where idProductos='"+ComprasTB.getValueAt(i, 1)+"'");
              
              Actualizar.executeUpdate();    
         }
        
    } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"error"+e.toString());
    }
   
}
   public void InsertarCompra(){
   
     String sql="INSERT INTO Compras(Fecha,idProveedores)values(?,?)";
     
    try {
        insertar=ConectarBD.prepareStatement(sql);
        insertar.setString(1, txtFecha.getText());
        insertar.setString(2,txtCodigoProveedor.getText());
        insertar.executeUpdate();
       
        
    JOptionPane.showMessageDialog(null,"Agregados Correcto ventas" );
       
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"error"+e.toString() );
    }
}
   public static String validadif(){
       String Compra="Compra";
       return Compra;
       
   }
   public void eliminar(){
    int fila=ComprasTB.getSelectedRow();
    if(fila>=0){
        Modelo.removeRow(fila);
        
    }else {
        JOptionPane.showMessageDialog(null, "Seleccione la fila");
    }
}
   public void EliminarAgregados(){
    int fila=ComprasTB.getRowCount();
    for(int i=fila-1; i>=0; i--){
        Modelo.removeRow(i);
    }
}
   public void Limpiar(){
       txtCantidad.setText("");
       txtCodigoProveedor.setText("");
       CodigoProductosCon.setText("");
       txtCostoTotal.setText("");
       txtExistencia.setText("");
       txtNombreProducto.setText("");
       txtNombreProveedor.setText("");
       txtPrecioCompra.setText("");
       
   }
    void CalcularTotal_Ventas(){
                
        int fila = 0;
        double valorCompra = 0;
        fila = ComprasTB.getRowCount();
        for (int f=0; f<fila; f++){
            valorCompra += Double.parseDouble(String.valueOf(ComprasTB.getModel().getValueAt(f, 6)));            
        }
        txtTotalPagar.setText(String.valueOf(valorCompra));
          
    }
    public void CostoTotal(){
    int Cantida=Integer.parseInt(txtCantidad.getText());
    float Precio=Float.parseFloat(txtPrecioCompra.getText());
    
    float CostoTotalve=Cantida*Precio;
    String pasarcosto=Float.toString(CostoTotalve);
    txtCostoTotal.setText(pasarcosto);
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton CargarPeroducto;
    public static javax.swing.JTextField CodigoProductosCon;
    private javax.swing.JButton CompraBT;
    private rojerusan.RSTableMetro ComprasTB;
    private javax.swing.JButton EliminarBT;
    private javax.swing.JButton ImprimirBT;
    private javax.swing.JButton NuevaCompraBoton;
    private javax.swing.JButton ProveedorCargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCodigoProveedor;
    public static javax.swing.JTextField txtCostoTotal;
    public static javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtNombreProducto;
    public static javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtNumeroCompra;
    public static javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
