/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofarmacia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel Arriola
 */
public class Marca extends javax.swing.JFrame {

   Conexion conectar=new Conexion();
   Connection ConectarBD=conectar.getConection();
   PreparedStatement Insertar=null;
   ResultSet rs;
   PreparedStatement Actualizar;
   Statement st;
    public Marca() {
        initComponents();
        marca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MarcaTB = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        NuevaMarca = new javax.swing.JButton();
        ActualizarBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MarcaTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        MarcaTB.setColorBackgoundHead(new java.awt.Color(51, 255, 255));
        MarcaTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcaTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MarcaTB);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 278, 460, 136));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 58, 75, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Marca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 108, 75, 40));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 108, 159, 40));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 53, 159, 40));

        NuevaMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NuevaMarca.setForeground(new java.awt.Color(0, 0, 0));
        NuevaMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar_1.png"))); // NOI18N
        NuevaMarca.setText("REGISTRAR MARCA");
        NuevaMarca.setContentAreaFilled(false);
        NuevaMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevaMarca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NuevaMarca.setIconTextGap(15);
        NuevaMarca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NuevaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(NuevaMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 180, 120));

        ActualizarBoton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ActualizarBoton.setForeground(new java.awt.Color(0, 0, 0));
        ActualizarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar (2).png"))); // NOI18N
        ActualizarBoton.setText("ACTUALIZAR MARCA");
        ActualizarBoton.setContentAreaFilled(false);
        ActualizarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActualizarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ActualizarBoton.setIconTextGap(15);
        ActualizarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 180, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salida.png"))); // NOI18N
        jLabel3.setText("REGRESAR");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaMarcaActionPerformed
        if(txtMarca.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"LLENAR CAMPOS OBLIGATORIOS","ERROR",JOptionPane.YES_NO_OPTION);
        }else{
            InsertarMarca();
            
        }
    }//GEN-LAST:event_NuevaMarcaActionPerformed

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
        ActualizarMarca();
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void MarcaTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaTBMouseClicked
        int fila=this.MarcaTB.getSelectedRow();
        this.txtID.setText(this.MarcaTB.getValueAt(fila, 0).toString());
        this.txtMarca.setText(this.MarcaTB.getValueAt(fila,1).toString());
    }//GEN-LAST:event_MarcaTBMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marca().setVisible(true);
            }
        });
    }

    public void InsertarMarca(){
        String Consulta="INSERT INTO Marca(NombreMarca)values(?)";
        try {
            Insertar=ConectarBD.prepareStatement(Consulta);
            Insertar.setString(1,txtMarca.getText());
            Insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Marca Agregada");
            Limpiar();
            marca();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error"+e.toString());
        }
    }
    public void marca(){
    DefaultTableModel Modelo=new DefaultTableModel();
    Modelo.addColumn("Codigo Marca");
    Modelo.addColumn("Nombre Marca");
    MarcaTB.setModel(Modelo);
    String Consulta="SELECT *FROM Marca";
    String Dato[]=new String[2];
    try {
    st=ConectarBD.createStatement();
     rs=st.executeQuery(Consulta);
     while(rs.next()){
         Dato[0]=rs.getString(1);
         Dato[1]=rs.getString(2);
         Modelo.addRow(Dato);
     }
        
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error"+e.toString());
    }
}
public void ActualizarMarca(){
    String Consulta="update Marca set NombreMarca='"+txtMarca.getText()+"'where idMarca='"+txtID.getText()+"'";
    try {
        Actualizar=ConectarBD.prepareStatement(Consulta);
        int Contador=Actualizar.executeUpdate();
        if(Contador>0){
            marca();
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione Fila");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error"+e.toString());
    }
}
public void Limpiar(){
    txtID.setText("");
    txtMarca.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private rojerusan.RSTableMetro MarcaTB;
    private javax.swing.JButton NuevaMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMarca;
    // End of variables declaration//GEN-END:variables
}
