/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofarmacia;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatDraculaContrastIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterContrastIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Joel Arriola
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Usuario
     */
    Conexion Conectar=new Conexion();
    Connection ConectarBD=Conectar.getConection();
    ResultSet rs;
    PreparedStatement Insertar=null;
    PreparedStatement Actualizar=null;
    PreparedStatement Eliminar=null;
    Statement st;
    
    public Usuario() {
        initComponents();
        VerDatosUsuario();
        ActualizarBoto.setEnabled(false);
        
        AutoCompleteDecorator.decorate(conCargo);
        AutoCompleteDecorator.decorate(conEstado);
        AutoCompleteDecorator.decorate(conNivel);
        CargarEstadoUsuario(conEstado);
        CargarNivelAcceso(conNivel);
        CargarTipoUsuario(conCargo);
       /* jButton1.putClientProperty( "FlatLaf.styleClass", "h1" );
        RegistrarBoto.putClientProperty( "FlatLaf.styleClass", "h1" );
        ActualizarBoto.putClientProperty( "FlatLaf.styleClass", "h1" );
        */
      
    }
    public void VerDatosUsuario(){
        DefaultTableModel Modelo=new DefaultTableModel();
        Modelo.addColumn("idUsuario");
        Modelo.addColumn("NombreUsuario");
        Modelo.addColumn("ApellidoUsuario");
        Modelo.addColumn("Usuario");
        Modelo.addColumn("Contraseña");
        Modelo.addColumn("Cargo");
        Modelo.addColumn("Estado");
        Modelo.addColumn("NivelAcceso");
        DatosUsuarios.setModel(Modelo);
        String Datos[] = new String[8];
        String Consulta="select u.idUsuario,u.NombreUsuario,u.ApellidoUsuario,u.Usuario,u.Contraseña, tu.NombreTipoUsuario As Cargo ,es.NombreEstado as Estado, cu.NombreAcceso as NivelAcceso\n" +
"from Usuario u, TipoUsuario tu, EstadoUsuario es, AccesoUsuario cu\n" +
"where u.idAccesoUsuario=cu.idAccesoUsuario and u.idEstadoUsuario=es.idEstadoUsuario and u.idTipoUsuario=tu.idTipoUsuario";
        try {
            st=ConectarBD.createStatement();
            rs=st.executeQuery(Consulta);
            while(rs.next()){
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Datos[5]=rs.getString(6);
                Datos[6]=rs.getString(7);
                Datos[7]=rs.getString(8);
                Modelo.addRow(Datos);
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Parece que tenemos un error"+e.toString());
        }
                
        
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        conCargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        conEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        conNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RegistrarBoto = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        ActualizarBoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatosUsuarios = new rojerusan.RSTableMetro();

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioEliminar.png"))); // NOI18N
        jMenuItem2.setText("ELIMINAR ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setPreferredSize(new java.awt.Dimension(890, 630));

        Fondo.setBackground(new java.awt.Color(51, 153, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(110, 207, 255));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 14, 149, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 53, 38));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 137, 100, 38));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 136, 149, 40));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 77, 100, 38));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 76, 152, 40));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cargo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 59, 100, 38));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 188, 149, 40));

        conCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(conCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 58, 150, 40));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(" Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 189, 100, 38));

        conEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(conEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 126, 150, 40));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 127, 100, 38));

        conNivel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(conNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 188, 150, 40));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nivel de Acceso");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 189, 100, 38));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 15, 100, 38));

        RegistrarBoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegistrarBoto.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarBoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar_1.png"))); // NOI18N
        RegistrarBoto.setText("REGISTRAR USUARIO");
        RegistrarBoto.setContentAreaFilled(false);
        RegistrarBoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarBoto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RegistrarBoto.setIconTextGap(15);
        RegistrarBoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarBotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarBotoMouseExited(evt);
            }
        });
        RegistrarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBotoActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarBoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 68, 251, 64));
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, 40));

        ActualizarBoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ActualizarBoto.setForeground(new java.awt.Color(0, 0, 0));
        ActualizarBoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar (2).png"))); // NOI18N
        ActualizarBoto.setText("ACTUALIZAR USUARIO");
        ActualizarBoto.setContentAreaFilled(false);
        ActualizarBoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActualizarBoto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ActualizarBoto.setIconTextGap(15);
        ActualizarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotoActionPerformed(evt);
            }
        });
        jPanel1.add(ActualizarBoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, 63));

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 260));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE LOS USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        DatosUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        DatosUsuarios.setComponentPopupMenu(jPopupMenu1);
        DatosUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatosUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DatosUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1240, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBotoActionPerformed
       if(txtNombre.getText().trim().isEmpty()||txtApellido.getText().trim().isEmpty()||txtUsuario.getText().trim().isEmpty()||txtContra.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"LLENAR CAMPOS OBLIGATORIOS","ERROR",JOptionPane.WARNING_MESSAGE);
           
        } else{
      RegistrarUsuario();
       }
    }//GEN-LAST:event_RegistrarBotoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed
   
    private void ActualizarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotoActionPerformed
        // TODO add your handling code here:
        ActualizarDatos();
    }//GEN-LAST:event_ActualizarBotoActionPerformed
 
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        RegistrarBoto.setEnabled(true);
        ActualizarBoto.setEnabled(false);
        Limpiar();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void RegistrarBotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarBotoMouseEntered
        // TODO add your handling code here:
         RegistrarBoto.setBackground(new Color(235, 176, 214));
    }//GEN-LAST:event_RegistrarBotoMouseEntered

    private void RegistrarBotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarBotoMouseExited
        // TODO add your handling code here:
         RegistrarBoto.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_RegistrarBotoMouseExited

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar=evt.getKeyChar();
        if((validar<'a'||validar>'z')&&(validar<'A'||validar>'Z'))evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
      char valida=evt.getKeyChar();
      if((valida<'a'||valida>'z')&&(valida<'A'||valida>'Z'))evt.consume();
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void DatosUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatosUsuariosMouseClicked
        ActualizarBoto.setEnabled(true);
        RegistrarBoto.setEnabled(false);
        int filas=this.DatosUsuarios.getSelectedRow();
        this.txtID.setText(this.DatosUsuarios.getValueAt(filas, 0).toString());
        this.txtNombre.setText(this.DatosUsuarios.getValueAt(filas, 1).toString());
        this.txtApellido.setText(this.DatosUsuarios.getValueAt(filas, 2).toString());
        this.txtUsuario.setText(this.DatosUsuarios.getValueAt(filas, 3).toString());
        this.txtContra.setText(this.DatosUsuarios.getValueAt(filas, 4).toString());
        this.conCargo.setSelectedItem(this.DatosUsuarios.getValueAt(filas, 5).toString());
        this.conEstado.setSelectedItem(this.DatosUsuarios.getValueAt(filas, 6).toString());
        this.conNivel.setSelectedItem(this.DatosUsuarios.getValueAt(filas, 7).toString());
    }//GEN-LAST:event_DatosUsuariosMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Esta Seguro de Eliminar Este usuario","ELIMINAR",JOptionPane.YES_NO_CANCEL_OPTION)==0){
            EliminarUsuario();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
public void EliminarUsuario(){
    try {
        Eliminar=ConectarBD.prepareStatement("Delete from Usuario where idUsuario='"+txtID.getText()+"'");
        int Contador=Eliminar.executeUpdate();
        if(Contador>0){
           // JOptionPane.showMessageDialog(null,"USUARIO ELIMINADO CON EXITO");
            VerDatosUsuario();
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione Fila");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error al eliminar"+ e.toString());
    }
}
public void ActualizarDatos(){
      int indice =1+conCargo.getSelectedIndex();
        int estado=1+conEstado.getSelectedIndex();
        int Nivel=1+conNivel.getSelectedIndex();
    try {
        
        Actualizar=ConectarBD.prepareStatement("UPDATE Usuario set NombreUsuario='"+txtNombre.getText()+"',ApellidoUsuario='"+txtApellido.getText()+"',Usuario='"+txtUsuario.getText()+"',Contraseña='"+txtContra.getText()+"',idTipoUsuario='"+indice+"',idEstadoUsuario='"+estado+"',idAccesoUsuario='"+Nivel+"' where idUsuario='"+txtID.getText()+"'");
        int Contador=Actualizar.executeUpdate();
        if(Contador>0){
           // JOptionPane.showMessageDialog(null,"Datos Actualizados Correctamente" );
            VerDatosUsuario();
        }else{
            JOptionPane.showMessageDialog(null,"No selecciono la fila " );
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Error Al Actualizar"+e.toString());
    }
}
 public void Limpiar(){
     txtID.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtContra.setText("");
        conCargo.setSelectedIndex(0);
        conEstado.setSelectedIndex(0);
        conNivel.setSelectedIndex(0);
        
    }
 public void CargarTipoUsuario(JComboBox Tipo){
     DefaultComboBoxModel Modelo=new DefaultComboBoxModel();
     Tipo.setModel(Modelo);
     String Consulta="select NombreTipoUsuario from TipoUsuario";
     try {
         st=ConectarBD.createStatement();
         rs=st.executeQuery(Consulta);
         while(rs.next()){
             Tipo.addItem(rs.getString("NombreTipoUsuario"));
         }
     } catch (Exception e) {
     }
     
 }
public void CargarEstadoUsuario(JComboBox estado){
    
    DefaultComboBoxModel Modelo=new DefaultComboBoxModel();
    estado.setModel(Modelo);
    String Consulta="select NombreEstado from EstadoUsuario";
    try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(Consulta);
        while(rs.next()){
            estado.addItem(rs.getString("NombreEstado"));
        }
    } catch (Exception e) {
    }
}

public void CargarNivelAcceso(JComboBox acceso){
    DefaultComboBoxModel Modelo=new DefaultComboBoxModel();
    acceso.setModel(Modelo);
    String consulta="select NombreAcceso from AccesoUsuario";
    try {
        st=ConectarBD.createStatement();
        rs=st.executeQuery(consulta);
        while(rs.next()){
            acceso.addItem(rs.getString("NombreAcceso"));
        }
    } catch (Exception e) {
    }
}
public void RegistrarUsuario(){
        String InsertarDatos="INSERT INTO Usuario(NombreUsuario,ApellidoUsuario,Usuario,Contraseña,idTipoUsuario,idEstadoUsuario,idAccesoUsuario)values(?,?,?,?,?,?,?);";
 
        String Agregar=(String) conCargo.getSelectedItem();
        int indice =1+conCargo.getSelectedIndex();
        int estado=1+conEstado.getSelectedIndex();
        int Nivel=1+conNivel.getSelectedIndex();
       
        try {
            Insertar=ConectarBD.prepareCall(InsertarDatos);
            Insertar.setString(1, txtNombre.getText());
            Insertar.setString(2,txtApellido.getText() );
            Insertar.setString(3,txtUsuario.getText() );
            Insertar.setString(4,txtContra.getText() );
            Insertar.setInt(5,indice);
            Insertar.setInt(6, estado);
            Insertar.setInt(7, Nivel);
            Insertar.executeUpdate();
           // JOptionPane.showMessageDialog(null, "Datos agregados Correctamente");
            VerDatosUsuario();
            Limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e.toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoto;
    private rojerusan.RSTableMetro DatosUsuarios;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton RegistrarBoto;
    private javax.swing.JComboBox<String> conCargo;
    private javax.swing.JComboBox<String> conEstado;
    private javax.swing.JComboBox<String> conNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
