/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofarmacia;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Joel Arriola
 */
public class Ventas extends javax.swing.JPanel {

    Conexion conectar=new Conexion();
   Connection ConectarBD=conectar.getConection();
   ResultSet rs;
   PreparedStatement insertar;
   PreparedStatement Actualizar;
   Statement st;
   DefaultTableModel Modelo=new DefaultTableModel();
   DefaultTableModel Total=new DefaultTableModel();
    public Ventas() {
        
        initComponents();
        Modelo.addColumn("CodigoProducto");
        Modelo.addColumn("CodigoVentas");
        Modelo.addColumn("NombreCliente");
        Modelo.addColumn("NombreProducto");
        Modelo.addColumn("Precio");
        Modelo.addColumn("Cantidad");
        Modelo.addColumn("Costo");
        
        this.VentasTB.setModel(Modelo);
         txtFecha.setDisabledTextColor(Color.BLUE);
        txtFecha.setText(Fecha());//pasamos la fecha al txtFecha
        txtFecha.setEnabled(false);//para que no se edite la fecha
      CargarNumeroVenta();
      bloquear();
      VentaBoton.setEnabled(false);
      AgregarBoton.setEnabled(false);
      ImprimirBT.setVisible(false);
      CancelarBoton.setEnabled(false);
      EliminarBoton.setEnabled(false);
    }

    public void CargarNumeroVenta(){
          String CodigoFactura=idVenta(); //cargamos el id de venta 
        int factura=Integer.parseInt(CodigoFactura);//comvertimos el id tipo int
        int resul=1+factura;// le sumamos 1
        String mostraCodigoFa=Integer.toString(resul);
        txtNumeroVenta.setDisabledTextColor(Color.BLUE);
        txtNumeroVenta.setText(mostraCodigoFa);// pasamos el id
        txtNumeroVenta.setEnabled(false);// para que no se pueda editar
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        CargarClientes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtNombreProducto = new javax.swing.JTextField();
        CodigoProductosCon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        CargarProducto = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtNumeroVenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        AgregarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ImprimirBT = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        VentaBoton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        VentasTB = new rojerusan.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        txtTotalPagar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(110, 207, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(110, 207, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo Cliente");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 108, 30));

        txtNombreCliente.setEditable(false);
        jPanel4.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 30, 210, 30));

        txtCodigoCliente.setEditable(false);
        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });
        jPanel4.add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 110, 30));

        CargarClientes.setBackground(new java.awt.Color(255, 255, 255));
        CargarClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarClientes.setForeground(new java.awt.Color(0, 0, 0));
        CargarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cargar.png"))); // NOI18N
        CargarClientes.setText("CARGAR DATOS CLIENTE");
        CargarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargarClientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CargarClientes.setIconTextGap(15);
        CargarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarClientesActionPerformed(evt);
            }
        });
        jPanel4.add(CargarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 260, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 130));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreProducto.setEditable(false);
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        jPanel5.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 210, 30));

        CodigoProductosCon.setEditable(false);
        CodigoProductosCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoProductosConKeyTyped(evt);
            }
        });
        jPanel5.add(CodigoProductosCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Producto");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Codigo Producto");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 108, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 30));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyTyped(evt);
            }
        });
        jPanel5.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Existencia");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 30));

        txtExistencia.setEditable(false);
        jPanel5.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 70, 30));

        CargarProducto.setBackground(new java.awt.Color(255, 255, 255));
        CargarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarProducto.setForeground(new java.awt.Color(0, 0, 0));
        CargarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cargar.png"))); // NOI18N
        CargarProducto.setText("CARGAR DATOS PRODUCTO");
        CargarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CargarProducto.setIconTextGap(15);
        CargarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarProductoActionPerformed(evt);
            }
        });
        jPanel5.add(CargarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 250, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 530, 180));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Costo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 530, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FECHA VENTA");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 26, 150, 48));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 80, 180, 53));

        txtNumeroVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNumeroVenta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(txtNumeroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 53));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NUMERO  VENTA");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 170, 48));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 300, 330));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarBoton.setForeground(new java.awt.Color(0, 0, 0));
        AgregarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Agregar.png"))); // NOI18N
        AgregarBoton.setText("AGREGAR");
        AgregarBoton.setContentAreaFilled(false);
        AgregarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AgregarBoton.setIconTextGap(15);
        AgregarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Agregar30.png"))); // NOI18N
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });
        jPanel8.add(AgregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 60));

        CancelarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelarBoton.setForeground(new java.awt.Color(0, 0, 0));
        CancelarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        CancelarBoton.setText("LIMPIAR");
        CancelarBoton.setContentAreaFilled(false);
        CancelarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CancelarBoton.setIconTextGap(15);
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });
        jPanel8.add(CancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 180, 60));

        EliminarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EliminarBoton.setForeground(new java.awt.Color(0, 0, 0));
        EliminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Elimina48.png"))); // NOI18N
        EliminarBoton.setText("ELIMINAR");
        EliminarBoton.setContentAreaFilled(false);
        EliminarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        EliminarBoton.setIconTextGap(15);
        EliminarBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Elimina32.png"))); // NOI18N
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });
        jPanel8.add(EliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, 60));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 620, 100));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        ImprimirBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ImprimirBT.setForeground(new java.awt.Color(0, 0, 0));
        ImprimirBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Imprimir (2).png"))); // NOI18N
        ImprimirBT.setText("IMPRIMIR");
        ImprimirBT.setContentAreaFilled(false);
        ImprimirBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImprimirBT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ImprimirBT.setIconTextGap(15);
        ImprimirBT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Imprimir32.png"))); // NOI18N
        ImprimirBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirBTActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/NuevaVC.png"))); // NOI18N
        jButton5.setText("NUEVA VENTA");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.setIconTextGap(15);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/Nueva32.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        VentaBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VentaBoton.setForeground(new java.awt.Color(0, 0, 0));
        VentaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconG/Guardar48.png"))); // NOI18N
        VentaBoton.setText("REALIZAR VENTA");
        VentaBoton.setContentAreaFilled(false);
        VentaBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentaBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        VentaBoton.setIconTextGap(15);
        VentaBoton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconP/guardar32.png"))); // NOI18N
        VentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(VentaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImprimirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(VentaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ImprimirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 280, 330));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(0, 0, 0));

        VentasTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(VentasTB);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total a pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        txtTotalPagar.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotalPagar.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(426, 426, 426))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1180, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void CodigoProductosConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoProductosConKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_CodigoProductosConKeyTyped

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyTyped
        char v=evt.getKeyChar();
        if((v<'0'||v>'9')&&(v<'.'||v>'.'))evt.consume();
    }//GEN-LAST:event_txtPrecioVentaKeyTyped

    private void CargarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarProductoActionPerformed

       MostrarProductosVenta pro=new MostrarProductosVenta();
       pro.Bloquear();
       pro.setVisible(true);
       txtCantidad.setText("");
      
    }//GEN-LAST:event_CargarProductoActionPerformed
public void  bloquear(){
    txtCantidad.setEnabled(false);
    txtNombreCliente.setEnabled(false);
    txtPrecioVenta.setEnabled(false);
    CargarClientes.setEnabled(false);
    CargarProducto.setEnabled(false);
    
}
public void Desbloquear(){
    txtCantidad.setEnabled(true);
    txtNombreCliente.setEnabled(true);
    txtPrecioVenta.setEnabled(true);
    CargarClientes.setEnabled(true);
    CargarProducto.setEnabled(true);
}
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed

        if(txtCantidad.getText().trim().isEmpty()||txtExistencia.getText().trim().isEmpty()||txtPrecioVenta.getText().trim().isEmpty()||CodigoProductosCon.getText().trim().isEmpty()||txtNombreCliente.getText().trim().isEmpty()||txtNombreProducto.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "POR FAVOR LLENE LOS CAMPOS");

        }else {
            int CantidadV=Integer.parseInt(txtCantidad.getText());
            int existenciap=Integer.parseInt(txtExistencia.getText());
            if(CantidadV>0){
                
            
            if(CantidadV>existenciap){
                JOptionPane.showMessageDialog(null,"No Contamos con la cantidad que pide");
            } else {

                llamar();
                CalcularTotal_Ventas();
               txtCantidad.setText("");
               txtCostoTotal.setText("");
               VentaBoton.setEnabled(true);
            }
            } else {
                JOptionPane.showMessageDialog(null, "La Cantidad No puede ser 0");
                CalcularTotal_Ventas();
            }
        }
       
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void VentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaBotonActionPerformed
if(JOptionPane.showConfirmDialog(null,"DESEA REALIZAR LA VENTA" ,"",JOptionPane.YES_NO_OPTION)==0){
        if(txtNombreCliente.getText().trim().isEmpty()||txtCodigoCliente.getText().trim().isEmpty()||txtNombreProducto.getText().trim().isEmpty()||txtPrecioVenta.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null,"LLENE TODO LOS CAMPOS OBLIGATORIOS");
}else {
       InsertarVentas();
       RealizarVentasss();
        ActualizarExistencia();
}
}
    }//GEN-LAST:event_VentaBotonActionPerformed

    private void CargarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarClientesActionPerformed
        DatosClientes clientes=new DatosClientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_CargarClientesActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
       Eliminar();
       CalcularTotal_Ventas();
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        EliminarAgregados();
        Limpiar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       CargarNumeroVenta();
       EliminarAgregados();
       Desbloquear();
       Limpiar();
     
      
      AgregarBoton.setEnabled(true);
      CancelarBoton.setEnabled(true);
      EliminarBoton.setEnabled(true);
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
    if(txtCantidad.getText().trim().isEmpty()||txtPrecioVenta.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Agrege cantidad");
    } else{
        CostoTotal();
    }
       
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtPrecioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyReleased
      
       
    }//GEN-LAST:event_txtPrecioVentaKeyReleased

    private void ImprimirBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirBTActionPerformed
   


     
    }//GEN-LAST:event_ImprimirBTActionPerformed
public void llamar(){
    String idVenta=idVenta();
    int codiV=Integer.parseInt(idVenta);
    int resul=1+codiV;
    String idVentaC=Integer.toString(resul);
    String cargar[]= new String[7];
  
    
    cargar[0]=CodigoProductosCon.getText();
    cargar[1]=txtNumeroVenta.getText();
    cargar[2]=txtNombreCliente.getText();
    cargar[3]=txtNombreProducto.getText();
    cargar[4]=txtPrecioVenta.getText();
    cargar[5]=txtCantidad.getText();
    cargar[6]=txtCostoTotal.getText();
    Modelo.addRow(cargar);
    
    
}
public void CostoTotal(){
    int Cantida=Integer.parseInt(txtCantidad.getText());
    float Precio=Float.parseFloat(txtPrecioVenta.getText());
    
    float CostoTotalve=Cantida*Precio;
    String pasarcosto=Float.toString(CostoTotalve);
    txtCostoTotal.setText(pasarcosto);
    
}
public void LimpiarAgregar(){
    
}
  public String Fecha(){
      Date Fecha=new Date();
      SimpleDateFormat FechaBD= new SimpleDateFormat("yyy-MM-dd");
      return FechaBD.format(Fecha);
      
  }
  public String idVenta(){
       String id=null;
       
       try {
           String consulta="select MAX(idVentas)as Ventas from Ventas";
           Actualizar=ConectarBD.prepareStatement(consulta);
           rs=Actualizar.executeQuery();
           if(rs.next()){
               String idCodigo=rs.getString("Ventas");
               id=(idCodigo);
               
            
           
           }
       } catch (Exception e) {
           System.out.println("Error "+e.toString());
       }
      return id;
      
   }
  
  public void RealizarVentasss(){
      try {
          for(int i=0;i<VentasTB.getRowCount();i++){
              insertar=ConectarBD.prepareStatement("INSERT INTO DetalleVenta(idProductos,idVentas,precio,cantidad,costoTotal)values(?,?,?,?,?)");
              insertar.setString(1, VentasTB.getValueAt(i, 0).toString());
              insertar.setString(2, VentasTB.getValueAt(i, 1).toString());
              insertar.setString(3, VentasTB.getValueAt(i, 4).toString());
              insertar.setString(4, VentasTB.getValueAt(i, 5).toString());
              insertar.setString(5, VentasTB.getValueAt(i, 6).toString());
              insertar.executeUpdate();
              
          }
          JOptionPane.showMessageDialog(null, "COMPRA REALIZADA CON EXITO");
      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Error"+e.toString());
      }
  }
  public void ActualizarExistencia(){
    try {
         for(int i=0;i<VentasTB.getRowCount();i++){
              Actualizar=ConectarBD.prepareStatement("update Productos set Existencia=Existencia-'"+VentasTB.getValueAt(i, 5)+"' where idProductos='"+VentasTB.getValueAt(i, 0)+"'");
              
              Actualizar.executeUpdate();    
         }
        
    } catch (Exception e) {
          JOptionPane.showMessageDialog(null,"error"+e.toString());
    }
  
}
   public void InsertarVentas(){
   
     String sql="INSERT INTO Ventas(Fecha,idClientes)values(?,?)";
     
    try {
        insertar=ConectarBD.prepareStatement(sql);
        insertar.setString(1, txtFecha.getText());
        insertar.setString(2,txtCodigoCliente.getText());
        insertar.executeUpdate();
       
        
    JOptionPane.showMessageDialog(null,"Agregados Correcto ventas" );
       
    } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"error"+e.toString() );
    }
}
      public void Eliminar(){
    int fila=VentasTB.getSelectedRow();
    if(fila>=0){
        Modelo.removeRow(fila);
        
    }else {
        JOptionPane.showMessageDialog(null, "Seleccione la fila");
    }
}
   public void EliminarAgregados(){
    int fila=VentasTB.getRowCount();
    for(int i=fila-1; i>=0; i--){
        Modelo.removeRow(i);
    }
}
   public void Limpiar(){
      // txtCantidad.setText("");
       CodigoProductosCon.setText("");
       txtCodigoCliente.setText("");
       txtCostoTotal.setText("");
       txtExistencia.setText("");
       txtNombreCliente.setText("");
       txtNombreProducto.setText("");
       txtPrecioVenta.setText("");
       txtTotalPagar.setText("");
   }
 
      void CalcularTotal_Ventas(){
                
        int fila = 0;
        double valorCompra = 0;
        fila = VentasTB.getRowCount();
        for (int f=0; f<fila; f++){
            valorCompra += Double.parseDouble(String.valueOf(VentasTB.getModel().getValueAt(f, 6)));            
        }
        txtTotalPagar.setText(String.valueOf(valorCompra));
          
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton CargarClientes;
    private javax.swing.JButton CargarProducto;
    public static javax.swing.JTextField CodigoProductosCon;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton ImprimirBT;
    private javax.swing.JButton VentaBoton;
    private rojerusan.RSTableMetro VentasTB;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCodigoCliente;
    public static javax.swing.JTextField txtCostoTotal;
    public static javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtNombreCliente;
    public static javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNumeroVenta;
    public static javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
